=== bcgov/harvest-restrictions/source.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/bcgov/harvest-restrictions/main/sources.schema.json",
    "title": "Resource extraction restriction data sources",
    "description": "List of data sources used to generate harvest restrictions, in order of hierarchy",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "alias": {
                "description": "Key to uniquely identify the data source when processing (lower case, _ separated)",
                "type": "string"
            },
            "description": {
                "description": "Description of the data source as defined",
                "type": "string"
            },
            "source_type": {
                "description": "Describes whether source is to be downloaded from BCGW (ie WFS using bcdata) or from FILE",
                "type": "string",
                "enum": ["BCGW", "FILE"]
            },
            "source": {
                "description": "Full name of the BCGW table to use as source (eg, WHSE_ADMIN_BOUNDARIES.CLAB_NATIONAL_PARKS) or url/path of a file based source readable by GDAL/OGR",
                "type": "string"
            },
            "layer": {
                "description": "Layer to use within a file based source",
                "type": "string"
            },
            "query": {
                "description": "Query to subset data in source/layer - ECQL for BCGW sources, OGR SQL for files",
                "type": ["string", "null"]
            },
            "primary_key": {
                "description": "The source column holding the primary key",
                "type": ["string", "null"]
            },
            "field_mapper": {
                "description": "Mapping of source column names to new column names",
                "type": "object"
            },
            "data": {
                "description": "Additional data to add to all records of the source, as key(column):value pair",
                "type": "object",
                "properties": {
                    "harvest_restriction": {
                        "description": "Forest harvesting restriction level associated with the designation",
                        "type": "integer",
                        "enum": [1, 2, 3, 4, 5, 6]
                    }
                }
            }
        },
        "required": ["alias", "description", "source_type", "source", "query", "field_mapper", "data"]
    }
}

=== bcgov/harvest-restrictions/sources.json
[
    {
        "alias": "park_national",
        "description": "National Park",
        "source_type": "BCGW",
        "source": "WHSE_ADMIN_BOUNDARIES.CLAB_NATIONAL_PARKS",
        "query": null,
        "field_mapper": {"name": "ENGLISH_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {   "alias": "park_er",
        "source_type": "BCGW",
        "description": "Ecological Reserve",
        "source": "WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW",
        "query": "PROTECTED_LANDS_DESIGNATION = 'ECOLOGICAL RESERVE'",
        "field_mapper": {"name": "PROTECTED_LANDS_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {
        "alias": "park_provincial",
        "source_type": "BCGW",
        "description": "Provincial Park",
        "source": "WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW",
        "query": "PROTECTED_LANDS_DESIGNATION = 'PROVINCIAL PARK'",
        "field_mapper": {"name": "PROTECTED_LANDS_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {
        "alias": "park_conservancy",
        "source_type": "BCGW",
        "description": "Conservancy",
        "source": "WHSE_TANTALIS.TA_CONSERVANCY_AREAS_SVW",
        "query": null,
        "field_mapper": {"name": "CONSERVANCY_AREA_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {
        "alias": "park_protectedarea",
        "source_type": "BCGW",
        "description": "Protected Area",
        "source": "WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW",
        "query": "PROTECTED_LANDS_DESIGNATION = 'PROTECTED AREA'",
        "field_mapper": {"name": "PROTECTED_LANDS_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {
        "alias": "heritage_site",
        "source_type": "BCGW",
        "description": "Heritage Site",
        "source": "WHSE_HUMAN_CULTURAL_ECONOMIC.HIST_HISTORIC_ENVIRONMNT_PA_SV",
        "query": null,
        "field_mapper": {"name": "COMMON_SITE_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {
        "alias": "park_recreationarea",
        "source_type": "BCGW",
        "description": "Recreation Area",
        "source": "WHSE_TANTALIS.TA_PARK_ECORES_PA_SVW",
        "query": "PROTECTED_LANDS_DESIGNATION = 'RECREATION AREA'",
        "field_mapper": {"name": "PROTECTED_LANDS_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {
        "alias": "park_regional",
        "source_type": "BCGW",
        "description": "Regional Park",
        "source": "WHSE_BASEMAPPING.GBA_LOCAL_REG_GREENSPACES_SP",
        "query": "PARK_TYPE LIKE 'Regional%'",
        "field_mapper": {"name": "PARK_NAME"},
        "data": {"harvest_restriction": 1}
    },
    {
        "alias": "uwr_no_harvest",
        "source_type": "BCGW",
        "description": "Ungulate Winter Range: No harvest",
        "source": "WHSE_WILDLIFE_MANAGEMENT.WCP_UNGULATE_WINTER_RANGE_SP",
        "query": "TIMBER_HARVEST_CODE = 'NO HARVEST ZONE'",
        "field_mapper": {"name": "UWR_NUMBER"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "wha_no_harvest",
        "source_type": "BCGW",
        "description": "Wildlife Habitat Area: No harvest",
        "source": "WHSE_WILDLIFE_MANAGEMENT.WCP_WILDLIFE_HABITAT_AREA_POLY",
        "query": "(TIMBER_HARVEST_CODE = 'NO HARVEST ZONE' AND FEATURE_NOTES NOT LIKE '%not a legal boundary%') OR(TIMBER_HARVEST_CODE = 'NO HARVEST ZONE' AND FEATURE_NOTES IS NULL)",
        "field_mapper": {"name": "COMMON_SPECIES_NAME"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "biodiv_mining_tourism_areas",
        "source_type": "BCGW",
        "description": "Biodiversity Mining and Tourism Area",
        "source": "WHSE_LAND_USE_PLANNING.RMP_PLAN_LEGAL_POLY_SVW",
        "query": "LEGAL_FEAT_OBJECTIVE = 'Biodiversity, Mining and Tourism Areas (BMTA)'",
        "field_mapper": {"name": "LEGAL_FEAT_ATRB_1_VALUE"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "sea_to_sky_wildland",
        "source_type": "BCGW",
        "description": "Sea to Sky Wildland Zone",
        "source": "WHSE_LAND_USE_PLANNING.RMP_PLAN_LEGAL_POLY_SVW",
        "query": "STRGC_LAND_RSRCE_PLAN_NAME = 'Sea to Sky Land and Resource Management Plan' AND LEGAL_FEAT_OBJECTIVE = 'Wildland Area'",
        "field_mapper": {"name": "LEGAL_FEAT_ATRB_4_VALUE"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "mk_wildland",
        "source_type": "BCGW",
        "description": "Special Wildland RMZ in Muskwa Kechia MA",
        "source": "WHSE_LAND_USE_PLANNING.RMP_PLAN_NON_LEGAL_POLY_SVW",
        "query": "NON_LEGAL_FEAT_ID IN (65488,65490,65491,65492,65497,65501,65508)",
        "field_mapper": {"name": "NON_LEGAL_FEAT_ATRB_4_VALUE"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "n_c_wildland",
        "source_type": "BCGW",
        "description": "Nlhaxten/Cayoosh Wildland Area",
        "source": "WHSE_LAND_USE_PLANNING.RMP_PLAN_LEGAL_POLY_SVW",
        "query": "STRGC_LAND_RSRCE_PLAN_NAME = 'Lillooet Land and Resource Management Plan' AND LEGAL_FEAT_OBJECTIVE = 'Wildland Area'",
        "field_mapper": {"name": "LEGAL_FEAT_ATRB_4_VALUE"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "s_cayoosh_wildland",
        "source_type": "BCGW",
        "description": "South Chilcotin Mountains Mining and Tourism Areas",
        "source": "WHSE_LAND_USE_PLANNING.RMP_PLAN_LEGAL_POLY_SVW",
        "query": "STRGC_LAND_RSRCE_PLAN_NAME = 'Lillooet Land and Resource Management Plan' AND LEGAL_FEAT_OBJECTIVE = 'Mining and Tourism Area'",
        "field_mapper": {"name": "LEGAL_FEAT_ATRB_4_VALUE"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "ngo_fee_simple",
        "source_type": "BCGW",
        "description": "NGO Fee Simple Conservation Lands",
        "source": "WHSE_LEGAL_ADMIN_BOUNDARIES.WCL_CONSERVATION_AREAS_NGO_SP",
        "query": null,
        "field_mapper": {"name": "CONSERVATION_AREAS_NGO_ID"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "great_bear_sfma",
        "source_type": "BCGW",
        "description": "Great Bear Rainforest (GBR) Special Forest Management Areas",
        "source": "WHSE_ADMIN_BOUNDARIES.FADM_SPECIAL_PROTECTION_AREA",
        "query": "PROTECTED_AREA_TYPE = 'SFMA'",
        "field_mapper": {"name": "PROTECTED_AREA_TYPE"},
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "great_bear_lrd",
        "source_type": "BCGW",
        "description": "Great Bear Rainforest (GBR) Landscape Reserve Design (LRD)",
        "source": "WHSE_LAND_USE_PLANNING.RMP_LANDSCAPE_RSRV_DESIGN_SP",
        "field_mapper": {"name": "LU_NAME"},
        "query": "LRD_STATUS = 'current'",
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "ogma_legal",
        "source_type": "BCGW",
        "description": "Old Growth Management Area (OGMA): Legal",
        "source": "WHSE_LAND_USE_PLANNING.RMP_OGMA_LEGAL_CURRENT_SVW",
        "field_mapper": {"name": "LEGAL_OGMA_PROVID"},
        "query": null,
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "great_bear_grizzly_class1",
        "description": "Class1 Coast Grizzly Bear Habitat (Coast LUP)",
        "source": "WHSE_LAND_USE_PLANNING.RMP_PLAN_LEGAL_POLY_SVW",
        "source_type": "BCGW",
        "field_mapper": {"name": "LEGAL_FEAT_ATRB_1_NAME"},
        "query": "LEGAL_FEAT_ATRB_1_NAME = 'GRIZZLY_BEAR_HABITAT_CLASS' AND LEGAL_FEAT_ATRB_1_VALUE = '1'",
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "ogma_nonlegal",
        "source_type": "BCGW",
        "description": "Old Growth Management Area (OGMA): Non-Legal",
        "source": "WHSE_LAND_USE_PLANNING.RMP_OGMA_NON_LEGAL_CURRENT_SVW",
        "field_mapper": {"name": null},
        "query": null,
        "data": {"harvest_restriction": 2}
    },
    {
        "alias": "private_conservation_lands_admin",
        "source_type": "BCGW",
        "description": "Private Conservation Land: Administered Land",
        "source": "WHSE_LEGAL_ADMIN_BOUNDARIES.WCL_CONSERVATION_LANDS_SP",
        "field_mapper": {"name": "SITE_NAME"},
        "query": "CONSERVATION_LAND_TYPE = 'Administered Lands'",
        "data": {"harvest_restriction": 3}
    },
    {
        "alias": "crd_water_supply_area",
        "source_type": "FILE",
        "description": "CRD Water Supply Area",
        "source": "/vsizip//vsis3/$BUCKET/harvest_restrictions/sources/CRD.gdb.zip",
        "layer": "WSA_Boundary",
        "primary_key": "OBJECTID",
        "field_mapper": {"name": "Name"},
        "query": null,
        "data": {"harvest_restriction": 3}
    },
    {
        "alias": "gvrd_water_supply_area",
        "source_type": "FILE",
        "description": "Greater Vancouver Water District",
        "source": "/vsizip//vsis3/$BUCKET/harvest_restrictions/sources/GVRD_watershed.gdb.zip",
        "layer": "GVRD_watershed",
        "query": null,
        "primary_key": "GlobalID",
        "field_mapper": {"name": "Name"},
        "data": {"harvest_restriction": 3}
    },
    {
        "alias": "wildlife_management_area",
        "source_type": "BCGW",
        "description": "Wildlife Management Area (WMA)",
        "source": "WHSE_TANTALIS.TA_WILDLIFE_MGMT_AREAS_SVW",
        "query": null,
        "field_mapper": {"name": "WILDLIFE_MANAGEMENT_AREA_NAME"},
        "data": {"harvest_restriction": 3}
    },
    {
        "alias": "creston_v_wma",
        "source_type": "BCGW",
        "description": "Creston Valley Wildlife Management Area",
        "source": "WHSE_TANTALIS.TA_WILDLIFE_MGMT_AREAS_SVW",
        "query": "ADMIN_AREA_SID = 5364",
        "field_mapper": {"name": "ADMIN_AREA_SID"},
        "data": {"harvest_restriction": 3}
    },
    {
        "alias": "vqo_preserve",
        "source_type": "BCGW",
        "description": "Visual Quality Objective (VQO): Preservation",
